<template>
  <div class="MJF62LC-g-j" id="csfdb">
    <div class="MJF62LC-g-i MJF62LC-g-e" id="csfb">
      <div tabindex="0">
        <input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text">

        <!-- Filters List -->
        <div>
          <div tabindex="0" class="MJF62LC-F-g" id="csrf" role="button" aria-haspopup="true" aria-expanded="false"><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="display: none;" aria-hidden="true" role="button" tabindex="-1" aria-label="Remove Roles filter"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-9" role="button">Roles</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVR42mNgGAWjYBQMf9ABxP8J4A5KLWnAY3gDtXzSQEvDsVnSQKs4aaCl4aNgFIwCMgEAYQgY/YabrZQAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <div tabindex="0" class="MJF62LC-F-g chosen" id="csdf" role="button" aria-haspopup="true" aria-expanded="false"><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="" role="button" tabindex="0" aria-label="Remove 2 Divisions filter"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-10" role="button">2 Divisions</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVR42mNgGAWjYBQMf9ABxP8J4A5KLWnAY3gDtXzSQEvDsVnSQKs4aaCl4aNgFIwCMgEAYQgY/YabrZQAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <div tabindex="0" class="MJF62LC-F-g" id="gjsf" role="button" aria-haspopup="true" aria-expanded="false"><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="display: none;" aria-hidden="true" role="button" tabindex="-1"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-15" role="button">Sort relevance</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAOElEQVR42mNgGAWjYNiBBiimmeH/obiBloZT3RJshtPMJ0M35dA8iBroEf4N9IjchtGUMwqGIQAA9Iwf6dTYJbUAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <div tabindex="0" class="MJF62LC-F-g" id="cseduf" role="button" aria-haspopup="true" aria-expanded="false" style=""><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="display: none;" aria-hidden="true" role="button" tabindex="-1" aria-label="Remove Education filter"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-11" role="button">Education</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVR42mNgGAWjYBQMf9ABxP8J4A5KLWnAY3gDtXzSQEvDsVnSQKs4aaCl4aNgFIwCMgEAYQgY/YabrZQAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <div tabindex="0" class="MJF62LC-F-g" id="csexpf" role="button" aria-haspopup="true" aria-expanded="false" style=""><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="display: none;" aria-hidden="true" role="button" tabindex="-1" aria-label="Remove Experience filter"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-12" role="button">Experience</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVR42mNgGAWjYBQMf9ABxP8J4A5KLWnAY3gDtXzSQEvDsVnSQKs4aaCl4aNgFIwCMgEAYQgY/YabrZQAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <div tabindex="0" class="MJF62LC-F-g" id="cstf" role="button" aria-haspopup="true" aria-expanded="false" style=""><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="display: none;" aria-hidden="true" role="button" tabindex="-1" aria-label="Remove Type filter"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-13" role="button">Type</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVR42mNgGAWjYBQMf9ABxP8J4A5KLWnAY3gDtXzSQEvDsVnSQKs4aaCl4aNgFIwCMgEAYQgY/YabrZQAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <div tabindex="0" class="MJF62LC-F-g" id="gjdpf" role="button" aria-haspopup="true" aria-expanded="false" style=""><input tabindex="-1" role="presentation" style="opacity: 0; height: 1px; width: 1px; z-index: -1; overflow: hidden; position: absolute;" type="text"><div><button type="button" class="MJF62LC-x-d MJF62LC-F-i" style="display: none;" aria-hidden="true" role="button" tabindex="-1" aria-label="Remove Date posted filter"><span><span class="material-icons-extended MJF62LC-u-c" role="presentation" aria-hidden="true">close</span></span></button><span class="MJF62LC-F-m no-wrap" id="gwt-uid-14" role="button">Date posted</span><button type="button" class="MJF62LC-x-d filter-drop" aria-hidden="true" tabindex="-1"><span><img role="presentation" aria-hidden="true" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVR42mNgGAWjYBQMf9ABxP8J4A5KLWnAY3gDtXzSQEvDsVnSQKs4aaCl4aNgFIwCMgEAYQgY/YabrZQAAAAASUVORK5CYII="></span></button><div style="display: none;" aria-hidden="true" class="MJF62LC-F-q"></div></div></div>

          <button type="button" class="MJF62LC-x-d MJF62LC-F-g MJF62LC-F-u" id="gjft" style="display: none;" aria-hidden="true">
            <span>
              <span class="MJF62LC-x-e captionMJF62LC-F-v">More filters</span>
            </span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
}
</script>
